# Generated by Django 4.2.13 on 2024-06-06 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='profile_pictures/')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(max_length=1000)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('body_type', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('drink', models.CharField(max_length=255)),
                ('drugs', models.CharField(max_length=50)),
                ('smokes', models.CharField(max_length=50)),
                ('likes_dogs', models.CharField(max_length=50)),
                ('likes_cat', models.CharField(max_length=50)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
