# Generated by Django 4.2.13 on 2024-06-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='likes_cat',
            new_name='likes_cats',
        ),
    ]
