# Generated by Django 4.2.13 on 2024-06-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0003_rename_likes_cat_profile_likes_cats'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
