# Generated by Django 4.2.13 on 2024-06-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0004_profile_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes_cats',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='likes_dogs',
        ),
        migrations.AddField(
            model_name='profile',
            name='diet',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Cotonou', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='offspring',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='orientation',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
