# Generated by Django 4.2.13 on 2024-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0005_remove_profile_likes_cats_remove_profile_likes_dogs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='diet',
            field=models.CharField(default='Végétarien', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='offspring',
            field=models.CharField(default="Je n'en ai pas, mais je souhaiterais en avoir", max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orientation',
            field=models.CharField(default='Hétérosexuel', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='f', max_length=10),
        ),
    ]
