# Generated by Django 4.2.13 on 2024-06-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0006_alter_profile_diet_alter_profile_offspring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
