# Generated by Django 4.2.13 on 2024-06-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0007_alter_utilisateur_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body_type',
            field=models.CharField(choices=[('Athlétique', 'Athlétique'), ('Mince', 'Mince'), ('Arrondie', 'Ronde')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orientation',
            field=models.CharField(choices=[('Hétérosexuel', 'Hétérosexuel'), ('Homosexuel', 'Homosexuel'), ('Bisexuel', 'Bisexuel')], default='Hétérosexuel', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('m', 'Homme'), ('f', 'Femme')], default='f', max_length=10),
        ),
    ]
