# Generated by Django 4.2.13 on 2024-06-12 00:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0008_alter_profile_body_type_alter_profile_orientation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='offspring',
        ),
        migrations.AddField(
            model_name='profile',
            name='enfant',
            field=models.CharField(default='Oui', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='langue',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='origin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='body_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diet',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='drink',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='drugs',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orientation',
            field=models.CharField(default='Hétérosexuel', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='f', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='smokes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 12, 1, 45, 51, 687327)),
        ),
        migrations.CreateModel(
            name='Préférences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('origin', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('physique', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('lifestyle', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
