# Generated by Django 4.2.13 on 2024-06-12 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0009_remove_profile_offspring_profile_enfant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 6, 12, 1, 46, 40, 609161)),
        ),
    ]
