# Generated by Django 4.2.13 on 2024-06-12 01:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0010_alter_utilisateur_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Youme.utilisateur'),
        ),
        migrations.AlterField(
            model_name='préférences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Youme.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 6, 12, 2, 42, 56, 898814)),
        ),
    ]
