# Generated by Django 4.2.13 on 2024-06-12 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0011_alter_profile_utilisateur_alter_préférences_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 6, 12, 2, 44, 59, 758522)),
        ),
    ]
