# Generated by Django 4.2.13 on 2024-06-12 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0013_alter_utilisateur_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='offspring',
            field=models.CharField(default='Non', max_length=255),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 6, 12, 9, 59, 17, 111038)),
        ),
    ]
