# Generated by Django 4.2.13 on 2024-06-14 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0016_alter_utilisateur_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(default='Lecture, Voyage', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='préférences',
            name='hobbies',
            field=models.CharField(default='Lecture, Voyage', max_length=225),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 6, 14, 16, 21, 53, 160680)),
        ),
    ]
