# Generated by Django 4.2.13 on 2024-06-15 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0018_alter_utilisateur_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='préférences',
            name='height',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 6, 15, 5, 41, 42, 821559)),
        ),
    ]
