# Generated by Django 4.2.13 on 2024-06-15 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0019_remove_préférences_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/images/profile.png', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 6, 15, 14, 52, 1, 857178)),
        ),
    ]
