# Generated by Django 4.2.13 on 2024-06-16 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0020_alter_profile_photo_alter_utilisateur_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body_type',
            field=models.CharField(choices=[('Minces', 'Mince'), ('En surpoids', 'En Surpoids'), ('Moyen', 'Moyen'), ('Athlétique', 'Athlétique')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orientation',
            field=models.CharField(choices=[('Hétérosexuel', 'Hétérosexuel'), ('Homosexuel', 'Homosexuel'), ('Bisexuel', 'Bisexuel')], default='Hétérosexuel', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('m', 'Homme'), ('f', 'Femme')], default='f', max_length=10),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 6, 16, 15, 51, 6, 58098)),
        ),
    ]
