# Generated by Django 4.2.13 on 2024-06-16 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0021_alter_profile_body_type_alter_profile_orientation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/images/profile.png', null=True, upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 6, 17, 0, 7, 14, 760412)),
        ),
    ]
