# Generated by Django 4.2.13 on 2024-06-19 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youme', '0030_alter_utilisateur_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 6, 19, 21, 32, 30, 384903)),
        ),
    ]
